# Generated by Django 4.2 on 2023-05-10 15:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Aid_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback_Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45)),
                ('email', models.EmailField(max_length=45)),
                ('feedback_text', models.TextField()),
                ('ratings', models.CharField(max_length=4)),
                ('date', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
    ]
