# Generated by Django 4.2 on 2023-05-11 20:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Aid_app', '0002_feedback_rating'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('Doctorid', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=45)),
                ('name', models.CharField(max_length=30)),
                ('address', models.TextField()),
                ('email', models.EmailField(max_length=30)),
                ('gender', models.CharField(max_length=6)),
                ('phone', models.CharField(max_length=45)),
                ('age', models.IntegerField()),
                ('cityName', models.CharField(max_length=45)),
                ('experience', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Health_Campaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Campaign_Name', models.CharField(max_length=100)),
                ('Organizer_Name', models.CharField(max_length=45)),
                ('venue', models.CharField(max_length=50)),
                ('Description', models.TextField()),
                ('Date', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
    ]
