# Generated by Django 4.2 on 2023-05-21 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Aid_app', '0003_doctor_health_campaign'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='fieldSpecialist',
            field=models.TextField(default=''),
        ),
    ]
