# Generated by Django 4.2 on 2023-05-27 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Aid_app', '0006_doctordetails_experience'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctordetails',
            name='visiting_hours',
            field=models.TextField(default=''),
        ),
    ]
