# Generated by Django 4.2 on 2023-05-29 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Aid_app', '0007_doctordetails_visiting_hours'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctordetails',
            name='experience',
        ),
        migrations.AlterField(
            model_name='doctordetails',
            name='doctor_pic',
            field=models.FileField(default='', upload_to='Aid_app/Doctorpic'),
        ),
    ]
