# Generated by Django 4.2 on 2023-05-29 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Aid_app', '0008_remove_doctordetails_experience_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctordetails',
            old_name='doctor',
            new_name='Doctor',
        ),
    ]
