# Generated by Django 4.2 on 2023-05-29 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Aid_app', '0009_rename_doctor_doctordetails_doctor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctordetails',
            old_name='Doctor',
            new_name='doctor',
        ),
    ]
